name: LobbySystem
version: '${project.version}'
main: me.iangry.lobbysystem.LobbySystem
author: iAngry
api-version: 1.19
commands:
  vote:
    description: Voting command
    usage: /<command> [args]
